from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register_user, name='register_user'),
    path('check-username/', views.check_username, name='check_username'),
    path('check-name/', views.check_name, name='check_name'),
    path('login/', views.login_view, name='login'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('admin-profile/', views.admin_profile, name='admin_profile'),
    path('manage-admins/', views.admin_view, name='manage_admins'),
    path('add-admin/', views.add_admin, name='add_admin'),
    path('update_admin/', views.update_admin, name='update_admin'),
    path('deactivate-admin/<int:admin_id>/', views.deactivate_admin, name='deactivate_admin'),
    path('activate-admin/<int:admin_id>/', views.activate_admin, name='activate_admin'),
    path('change-password/', views.change_password, name='change_password'),
    path('manage-users/', views.active_user, name='active_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('sensors/', views.sensors, name='sensors'),
    path('update-sensor/', views.update_sensor, name='update_sensor'),
    path('delete-sensor/<int:sensor_id>/', views.delete_sensor, name='delete_sensor'),
    path('add-sensor/', views.add_sensor, name='add_sensor'),
    path('weather-reports/', views.weather_reports, name='weather_reports'),
    path('daily-reports/', views.daily_reports, name='daily_reports'),
    path('monthly-reports/', views.monthly_reports, name='monthly_reports'),
    path('api/data/', views.receive_sensor_data, name='receive_sensor_data'),
    path('send-alert/', views.send_alert, name='send_alert'),
]
